## Using Regular Expressions
What if we wanted to do something more complicated, like search for all elements in a column that being with either "A" or "B"?  
  
We can use something called **Regular Expressions**, aka **Regex**, to solve this

## Using Regular Expressions {.build}
Think of regex as a separate language, with it's own code, syntax, and rules.  
  
Regex rules allow complex matching patterns for strings, to ensure matching *exactly* the content desired
  
It is far too complex to cover in its entirely here, but here is one specific example.  
  
**GOAL**: identify all of the patients that have a father with a history of disease, but excluding grandfathers in the results. 
  
## Regular Expression Example {.build}
<div class="red2"> Example </div>  
Our goal is to identify all elements of `r df_2_col` that begin with either the letter "A" or the letter "B".  

First, we need to specify a pattern that captures this. This pattern is - `(A|B)`.   
  
Then, we want this pattern to appear at the beginning of the word, so we add the regex `^` symbol.    

Our completed regex looks like:    

`str_count(`r dataframe_name`$`r df_2_col`, '^(A|B)')`

```{r regex1, exercise=TRUE}


```

## Regex resources
- The stringr cheatsheet shown above is a great resource  
- Here the tidyverse website with a link to its vignette  
  
<center><iframe src="https://stringr.tidyverse.org/articles/regular-expressions.html"></iframe></center>  
