###healthcare dataset
library(here)
library(readr)
library(dplyr)
#set these variables
file_name <- 'cdc.rds'
dataframe_name <-'cdc'
dataframe_title <-'CDC Dataset'
dataframe_source <-'This data set dates from 1988 and consists of four databases: Cleveland, Hungary, Switzerland, and Long Beach V.'
dataframe_desc <-'The complete data set contains 76 attributes, including a predicted attribute generated by ML models to predict heart failure. However, all published experiments refer to using a subset of 14 attributes, which we will use for this class'
dataframe_about <- 'COVID19'
path_to_data <- 'tutorials/bespokelecture/data/cdc.rds'
data <- readRDS(path_to_data)
cdc<- data
#join
dataframe_join_file_name <-'cdc_unweighted.csv'
dataframe_join_name <- 'Ethnicity'
dataframe_join_about <- 'pseudo-patient histories'
data2 <- read_csv('tutorials/bespokelecture/data/cdc_unweighted.csv')
joined <- read_csv('tutorials/bespokelecture/data/cdc_unweighted.csv') %>%  right_join(cdc,by = 'Ethnicity')
#joined
dataframe_joined_name <- 'joined'
