---
title: "making COVID19 dataset"
author: "Akshay Bareja"
date: "6/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Load and process data
```{r load and process}
# Source and description of data - https://dev.socrata.com/foundry/data.cdc.gov/pj7m-y5uh
# MAKE NOTE OF DATE OF MOST RECENT DATA - 06/17/2020
cdc <- read_csv("Provisional_Death_Counts_for_Coronavirus_Disease__COVID-19___Weekly_State-Specific_Data_Updates.csv")
cdc %>% 
  select(-Footnote) -> cdc

cdc %>% 
  filter(Indicator == "Distribution of COVID-19 deaths (%)") -> cdc_dist

cdc %>% 
  filter(Indicator == "Weighted distribution of population (%)") -> cdc_weighted

cdc_dist %>% 
  pivot_longer(cols = `Non-Hispanic White`:Other,
               names_to = "Ethnicity",
               values_to = "Distribution") %>% 
  select(-Indicator) -> cdc_dist

cdc_weighted %>% 
  pivot_longer(cols = `Non-Hispanic White`:Other,
               names_to = "Ethnicity",
               values_to = "Weighted Distribution") %>% 
  select(-Indicator) -> cdc_weighted

cdc_df <- bind_cols(cdc_dist[ , -1], cdc_weighted[ , 4])
# need an `id` column
cdc_df %>% 
  drop_na() -> cdc_df
cdc_df$row_id <- 1:nrow(cdc_df)

saveRDS(cdc_df, "cdc.rds")

# dataset for merge 
cdc %>% 
  filter(Indicator == "Unweighted distribution of population (%)") -> cdc_unweighted

cdc_unweighted %>% 
  pivot_longer(cols = `Non-Hispanic White`:Other,
               names_to = "Ethnicity",
               values_to = "Unweighted Distribution") %>% 
  select(-Indicator, -`Data as of`, -State) -> cdc_unweighted

cdc_unweighted$row_id <- 1:nrow(cdc_unweighted)
write_csv(cdc_unweighted, "cdc_unweighted.csv") # join on `Ethnicity` column

```

