library(rstudioapi)

make_metadata <- function(YourFolder, YourRdsFile, DataframeName, DataframeTitle, DataframeSource, DataframeDescription, DataframeAbout, JoinFileName, JoinName, JoinAbout, JoinVariable, JoinedName){
  documentNew(
    paste0("###healthcare dataset\nlibrary(here)\nlibrary(readr)\nlibrary(dplyr)\n#set these variables",
           "\nfile_name <- ", "'", YourRdsFile, "'",
           "\ndataframe_name <-", "'", DataframeName, "'",
           "\ndataframe_title <-", "'", DataframeTitle, "'",
           "\ndataframe_source <-", "'", DataframeSource, "'",
           "\ndataframe_desc <-", "'", DataframeDescription, "'",
           "\ndataframe_about <- ", "'", DataframeAbout, "'",
           "\npath_to_data <- here::here('inst/tutorials/", YourFolder,"/data', " , "'",YourRdsFile ,"'" ,")",
           "\ndata <- readRDS(path_to_data)",
           "\n" , DataframeName, "<- data", #set this object as the same as dataframe_name, makes it available in the learnr chunks",
           "\n#join",
           "\ndataframe_join_file_name <-", "'", JoinFileName, "'",
           "\ndataframe_join_name <- ", "'", JoinName, "'",
           "\ndataframe_join_about <- ", "'", JoinAbout, "'",
           "\ndata2 <- read_csv(here::here('inst/tutorials/", YourFolder,"/data', " , "'" ,JoinFileName , "'" ,"))",
           "\njoined <- read_csv(here::here('inst/tutorials/", YourFolder,"/data', " , "'"  ,JoinFileName , "'",")) %>%  right_join(", DataframeName, ",",  "by = ", "'",JoinVariable, "')",
           "\n#joined",
           "\ndataframe_joined_name <- ", "'", JoinedName, "'"
    ),
    type = "r",
    position = document_position(0, 0),
    execute = FALSE
  )
}

# Example
make_metadata(YourFolder = "plusDS_session1",
           YourRdsFile = "cdc.rds",
           DataframeName = "cdc",
           DataframeTitle = "CDC Dataset",
           DataframeSource = "This data set dates from 1988 and consists of four databases: Cleveland, Hungary, Switzerland, and Long Beach V.",
           DataframeDescription = "The complete data set contains 76 attributes, including a predicted attribute generated by ML models to predict heart failure. However, all published experiments refer to using a subset of 14 attributes, which we will use for this class",
           DataframeAbout = "COVID19",
           JoinFileName = "cdc_unweighted.csv",
           JoinName = "Ethnicity",
           JoinAbout = "pseudo-patient histories",
           JoinVariable = "Ethnicity",
           JoinedName = "joined") # call this `make_metadata()`?

bespoke <- function(df, YourFolder){
  documentNew(
    paste0("set.seed(42)\nlibrary(tidyverse)\n#load dataset for for class",
           "\nsource(here::here('inst/tutorials/", YourFolder,"/code', "  ,"'",df,"'","))", "#loads dataset-specific variables",
           "\n#make dataframes",
           "\ndf_input <- data # df MUST contain at least one character and one numeric variable",
           "\ndf_numeric <- df_input %>% select_if(~is.numeric(.) & length(unique(.)) > 10) %>% select(-contains('id'))",
           "\ndf_character <- df_input %>% select_if(~is.character(.)) %>% select(-contains('id'))",
           "\ndf_id <- df_input %>% select(contains('id')) #make sure a variable contains 'id'!!!",
           "\ndf_input2 <- data2",
           "\ndf_joined_character <- df_input2 %>% select_if(~is.character(.)) %>% select(-contains('id'))",
           "\n#df_joined <- joined",
           "\n#do I use these?",
           "\ndf_numeric_select <- df_numeric[sample(1:ncol(df_numeric), 1)] # choose a random numeric column",
           "\ndf_numeric_filter <- df_numeric_select[sample(1:nrow(df_numeric), 1),] # choose a random number within that column",
           "\ndf_character_select <- df_character[sample(1:ncol(df_character), 1)] # choose a random character column",
           "\ndf_character_filter <- df_character_select[sample(1:nrow(df_character), 1),] # choose a random value within that column",
           "\n#sample and set global variables",
           "\ndf_numerics <- sample(colnames(df_numeric), 2)",
           "\ndf_numeric1_name <- df_numerics[1]",
           "\ndf_numeric1_vec <- df_input %>% select(matches(df_numeric1_name)) %>% pull()",
           "\ndf_numeric2_name <- df_numerics[2]",
           "\ndf_numeric2_vec <- df_input %>% select(matches(df_numeric2_name)) %>% pull()",
           "\ndf_characters <- sample(colnames(df_character), 2)",
           "\ndf_char1_name <- df_characters[1]",
           "\ndf_char1_vec <- df_input %>% select(matches(df_char1_name)) %>% pull() #not used",
           "\ndf_char2_name <- df_characters[2]",
           "\ndf_char2_vec <- df_input %>% select(matches(df_char2_name)) %>% pull() #not used",
           "\ndf_id_name <- sample(colnames(df_id), 1)",
           "\ndf_id_vec <- df_input %>% select(matches(df_id_name)) #not used",
           "\ndf_joined_strings <- sample(colnames(df_joined_character), 3) #fix this (should be 2)",
           "\ndf_joined_string1_name <- df_joined_strings[1] #family_history",
           "\ndf_joined_string2_name <- df_joined_strings[2] #medication_hx",
           "\ndf_joined_string3_name <- df_joined_strings[3] #health_status"),
    type = "r",
    position = document_position(0, 0),
    execute = FALSE
  )
}

# Example
bespoke("metadata.R", YourFolder = "plusDS_session1")


